name: math_nim_game
description: 수학 님 게임 - 수아(AI)와 1:1 두뇌싸움 수학 전략 게임

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  google_mobile_ads: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
